"""empty message

Revision ID: 765df44b1cdd
Revises: 0e1458953347
Create Date: 2025-08-14 15:45:49.208032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765df44b1cdd'
down_revision = '0e1458953347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_comment_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comment_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
