"""empty message

Revision ID: cbcc5bef4e61
Revises: 43f07c038342
Create Date: 2025-08-14 15:59:54.113215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcc5bef4e61'
down_revision = '43f07c038342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('followed_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_follower_followed_id'), ['followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follower_follower_id'), ['follower_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_follower_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follower_followed_id'))
        batch_op.drop_column('followed_id')
        batch_op.drop_column('follower_id')

    # ### end Alembic commands ###
